/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as HubRouteImport } from './routes/_hub'
import { Route as HubIndexRouteImport } from './routes/_hub.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as HubComposeScriptRouteImport } from './routes/_hub.compose-script'
import { Route as HubComposeBlogRouteImport } from './routes/_hub.compose-blog'
import { Route as HubComposeRouteImport } from './routes/_hub.compose'
import { Route as HubProjectIdRouteImport } from './routes/_hub.$projectId'
import { Route as ProjectsProjectIdLaunchRouteImport } from './routes/projects.$projectId.launch'
import { Route as ProjectsProjectIdBookRouteImport } from './routes/projects.$projectId.book'
import { Route as HubProjectIdVoiceRouteImport } from './routes/_hub.$projectId.voice'
import { Route as HubProjectIdOutlineRouteImport } from './routes/_hub.$projectId.outline'
import { Route as HubProjectIdMarketplaceRouteImport } from './routes/_hub.$projectId.marketplace'
import { Route as HubProjectIdCanvasRouteImport } from './routes/_hub.$projectId.canvas'
import { Route as HubProjectIdBookRouteImport } from './routes/_hub.$projectId.book'
import { Route as HubScriptsScriptIdIndexRouteImport } from './routes/_hub.scripts.$scriptId.index'
import { Route as HubBlogsBlogIdIndexRouteImport } from './routes/_hub.blogs.$blogId.index'
import { Route as ProjectsProjectIdChaptersChapterIdRouteImport } from './routes/projects.$projectId.chapters.$chapterId'
import { Route as HubScriptsScriptIdStructureRouteImport } from './routes/_hub.scripts.$scriptId.structure'
import { Route as HubBlogsBlogIdStructureRouteImport } from './routes/_hub.blogs.$blogId.structure'
import { Route as HubProjectIdChaptersChapterIdRouteImport } from './routes/_hub.$projectId.chapters.$chapterId'
import { Route as HubScriptsScriptIdScenesSceneIdRouteImport } from './routes/_hub.scripts.$scriptId.scenes.$sceneId'
import { Route as HubBlogsBlogIdPostsPostIdRouteImport } from './routes/_hub.blogs.$blogId.posts.$postId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/_hub',
  getParentRoute: () => rootRouteImport,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const HubComposeScriptRoute = HubComposeScriptRouteImport.update({
  id: '/compose-script',
  path: '/compose-script',
  getParentRoute: () => HubRoute,
} as any)
const HubComposeBlogRoute = HubComposeBlogRouteImport.update({
  id: '/compose-blog',
  path: '/compose-blog',
  getParentRoute: () => HubRoute,
} as any)
const HubComposeRoute = HubComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => HubRoute,
} as any)
const HubProjectIdRoute = HubProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => HubRoute,
} as any)
const ProjectsProjectIdLaunchRoute = ProjectsProjectIdLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBookRoute = ProjectsProjectIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const HubProjectIdVoiceRoute = HubProjectIdVoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => HubProjectIdRoute,
} as any)
const HubProjectIdOutlineRoute = HubProjectIdOutlineRouteImport.update({
  id: '/outline',
  path: '/outline',
  getParentRoute: () => HubProjectIdRoute,
} as any)
const HubProjectIdMarketplaceRoute = HubProjectIdMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => HubProjectIdRoute,
} as any)
const HubProjectIdCanvasRoute = HubProjectIdCanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => HubProjectIdRoute,
} as any)
const HubProjectIdBookRoute = HubProjectIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => HubProjectIdRoute,
} as any)
const HubScriptsScriptIdIndexRoute = HubScriptsScriptIdIndexRouteImport.update({
  id: '/scripts/$scriptId/',
  path: '/scripts/$scriptId/',
  getParentRoute: () => HubRoute,
} as any)
const HubBlogsBlogIdIndexRoute = HubBlogsBlogIdIndexRouteImport.update({
  id: '/blogs/$blogId/',
  path: '/blogs/$blogId/',
  getParentRoute: () => HubRoute,
} as any)
const ProjectsProjectIdChaptersChapterIdRoute =
  ProjectsProjectIdChaptersChapterIdRouteImport.update({
    id: '/chapters/$chapterId',
    path: '/chapters/$chapterId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const HubScriptsScriptIdStructureRoute =
  HubScriptsScriptIdStructureRouteImport.update({
    id: '/scripts/$scriptId/structure',
    path: '/scripts/$scriptId/structure',
    getParentRoute: () => HubRoute,
  } as any)
const HubBlogsBlogIdStructureRoute = HubBlogsBlogIdStructureRouteImport.update({
  id: '/blogs/$blogId/structure',
  path: '/blogs/$blogId/structure',
  getParentRoute: () => HubRoute,
} as any)
const HubProjectIdChaptersChapterIdRoute =
  HubProjectIdChaptersChapterIdRouteImport.update({
    id: '/chapters/$chapterId',
    path: '/chapters/$chapterId',
    getParentRoute: () => HubProjectIdRoute,
  } as any)
const HubScriptsScriptIdScenesSceneIdRoute =
  HubScriptsScriptIdScenesSceneIdRouteImport.update({
    id: '/scripts/$scriptId/scenes/$sceneId',
    path: '/scripts/$scriptId/scenes/$sceneId',
    getParentRoute: () => HubRoute,
  } as any)
const HubBlogsBlogIdPostsPostIdRoute =
  HubBlogsBlogIdPostsPostIdRouteImport.update({
    id: '/blogs/$blogId/posts/$postId',
    path: '/blogs/$blogId/posts/$postId',
    getParentRoute: () => HubRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof HubIndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/scout': typeof ScoutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
  '/$projectId': typeof HubProjectIdRouteWithChildren
  '/compose': typeof HubComposeRoute
  '/compose-blog': typeof HubComposeBlogRoute
  '/compose-script': typeof HubComposeScriptRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/$projectId/book': typeof HubProjectIdBookRoute
  '/$projectId/canvas': typeof HubProjectIdCanvasRoute
  '/$projectId/marketplace': typeof HubProjectIdMarketplaceRoute
  '/$projectId/outline': typeof HubProjectIdOutlineRoute
  '/$projectId/voice': typeof HubProjectIdVoiceRoute
  '/projects/$projectId/book': typeof ProjectsProjectIdBookRoute
  '/projects/$projectId/launch': typeof ProjectsProjectIdLaunchRoute
  '/$projectId/chapters/$chapterId': typeof HubProjectIdChaptersChapterIdRoute
  '/blogs/$blogId/structure': typeof HubBlogsBlogIdStructureRoute
  '/scripts/$scriptId/structure': typeof HubScriptsScriptIdStructureRoute
  '/projects/$projectId/chapters/$chapterId': typeof ProjectsProjectIdChaptersChapterIdRoute
  '/blogs/$blogId/': typeof HubBlogsBlogIdIndexRoute
  '/scripts/$scriptId/': typeof HubScriptsScriptIdIndexRoute
  '/blogs/$blogId/posts/$postId': typeof HubBlogsBlogIdPostsPostIdRoute
  '/scripts/$scriptId/scenes/$sceneId': typeof HubScriptsScriptIdScenesSceneIdRoute
}
export interface FileRoutesByTo {
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/scout': typeof ScoutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
  '/$projectId': typeof HubProjectIdRouteWithChildren
  '/compose': typeof HubComposeRoute
  '/compose-blog': typeof HubComposeBlogRoute
  '/compose-script': typeof HubComposeScriptRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/': typeof HubIndexRoute
  '/$projectId/book': typeof HubProjectIdBookRoute
  '/$projectId/canvas': typeof HubProjectIdCanvasRoute
  '/$projectId/marketplace': typeof HubProjectIdMarketplaceRoute
  '/$projectId/outline': typeof HubProjectIdOutlineRoute
  '/$projectId/voice': typeof HubProjectIdVoiceRoute
  '/projects/$projectId/book': typeof ProjectsProjectIdBookRoute
  '/projects/$projectId/launch': typeof ProjectsProjectIdLaunchRoute
  '/$projectId/chapters/$chapterId': typeof HubProjectIdChaptersChapterIdRoute
  '/blogs/$blogId/structure': typeof HubBlogsBlogIdStructureRoute
  '/scripts/$scriptId/structure': typeof HubScriptsScriptIdStructureRoute
  '/projects/$projectId/chapters/$chapterId': typeof ProjectsProjectIdChaptersChapterIdRoute
  '/blogs/$blogId': typeof HubBlogsBlogIdIndexRoute
  '/scripts/$scriptId': typeof HubScriptsScriptIdIndexRoute
  '/blogs/$blogId/posts/$postId': typeof HubBlogsBlogIdPostsPostIdRoute
  '/scripts/$scriptId/scenes/$sceneId': typeof HubScriptsScriptIdScenesSceneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_hub': typeof HubRouteWithChildren
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/scout': typeof ScoutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/welcome': typeof WelcomeRoute
  '/_hub/$projectId': typeof HubProjectIdRouteWithChildren
  '/_hub/compose': typeof HubComposeRoute
  '/_hub/compose-blog': typeof HubComposeBlogRoute
  '/_hub/compose-script': typeof HubComposeScriptRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/_hub/': typeof HubIndexRoute
  '/_hub/$projectId/book': typeof HubProjectIdBookRoute
  '/_hub/$projectId/canvas': typeof HubProjectIdCanvasRoute
  '/_hub/$projectId/marketplace': typeof HubProjectIdMarketplaceRoute
  '/_hub/$projectId/outline': typeof HubProjectIdOutlineRoute
  '/_hub/$projectId/voice': typeof HubProjectIdVoiceRoute
  '/projects/$projectId/book': typeof ProjectsProjectIdBookRoute
  '/projects/$projectId/launch': typeof ProjectsProjectIdLaunchRoute
  '/_hub/$projectId/chapters/$chapterId': typeof HubProjectIdChaptersChapterIdRoute
  '/_hub/blogs/$blogId/structure': typeof HubBlogsBlogIdStructureRoute
  '/_hub/scripts/$scriptId/structure': typeof HubScriptsScriptIdStructureRoute
  '/projects/$projectId/chapters/$chapterId': typeof ProjectsProjectIdChaptersChapterIdRoute
  '/_hub/blogs/$blogId/': typeof HubBlogsBlogIdIndexRoute
  '/_hub/scripts/$scriptId/': typeof HubScriptsScriptIdIndexRoute
  '/_hub/blogs/$blogId/posts/$postId': typeof HubBlogsBlogIdPostsPostIdRoute
  '/_hub/scripts/$scriptId/scenes/$sceneId': typeof HubScriptsScriptIdScenesSceneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/scout'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/$projectId'
    | '/compose'
    | '/compose-blog'
    | '/compose-script'
    | '/projects/$projectId'
    | '/$projectId/book'
    | '/$projectId/canvas'
    | '/$projectId/marketplace'
    | '/$projectId/outline'
    | '/$projectId/voice'
    | '/projects/$projectId/book'
    | '/projects/$projectId/launch'
    | '/$projectId/chapters/$chapterId'
    | '/blogs/$blogId/structure'
    | '/scripts/$scriptId/structure'
    | '/projects/$projectId/chapters/$chapterId'
    | '/blogs/$blogId/'
    | '/scripts/$scriptId/'
    | '/blogs/$blogId/posts/$postId'
    | '/scripts/$scriptId/scenes/$sceneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/scout'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/$projectId'
    | '/compose'
    | '/compose-blog'
    | '/compose-script'
    | '/projects/$projectId'
    | '/'
    | '/$projectId/book'
    | '/$projectId/canvas'
    | '/$projectId/marketplace'
    | '/$projectId/outline'
    | '/$projectId/voice'
    | '/projects/$projectId/book'
    | '/projects/$projectId/launch'
    | '/$projectId/chapters/$chapterId'
    | '/blogs/$blogId/structure'
    | '/scripts/$scriptId/structure'
    | '/projects/$projectId/chapters/$chapterId'
    | '/blogs/$blogId'
    | '/scripts/$scriptId'
    | '/blogs/$blogId/posts/$postId'
    | '/scripts/$scriptId/scenes/$sceneId'
  id:
    | '__root__'
    | '/_hub'
    | '/account'
    | '/admin'
    | '/dashboard'
    | '/scout'
    | '/sign-in'
    | '/sign-up'
    | '/welcome'
    | '/_hub/$projectId'
    | '/_hub/compose'
    | '/_hub/compose-blog'
    | '/_hub/compose-script'
    | '/projects/$projectId'
    | '/_hub/'
    | '/_hub/$projectId/book'
    | '/_hub/$projectId/canvas'
    | '/_hub/$projectId/marketplace'
    | '/_hub/$projectId/outline'
    | '/_hub/$projectId/voice'
    | '/projects/$projectId/book'
    | '/projects/$projectId/launch'
    | '/_hub/$projectId/chapters/$chapterId'
    | '/_hub/blogs/$blogId/structure'
    | '/_hub/scripts/$scriptId/structure'
    | '/projects/$projectId/chapters/$chapterId'
    | '/_hub/blogs/$blogId/'
    | '/_hub/scripts/$scriptId/'
    | '/_hub/blogs/$blogId/posts/$postId'
    | '/_hub/scripts/$scriptId/scenes/$sceneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  HubRoute: typeof HubRouteWithChildren
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ScoutRoute: typeof ScoutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WelcomeRoute: typeof WelcomeRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub': {
      id: '/_hub'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/': {
      id: '/_hub/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_hub/compose-script': {
      id: '/_hub/compose-script'
      path: '/compose-script'
      fullPath: '/compose-script'
      preLoaderRoute: typeof HubComposeScriptRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/compose-blog': {
      id: '/_hub/compose-blog'
      path: '/compose-blog'
      fullPath: '/compose-blog'
      preLoaderRoute: typeof HubComposeBlogRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/compose': {
      id: '/_hub/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof HubComposeRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/$projectId': {
      id: '/_hub/$projectId'
      path: '/$projectId'
      fullPath: '/$projectId'
      preLoaderRoute: typeof HubProjectIdRouteImport
      parentRoute: typeof HubRoute
    }
    '/projects/$projectId/launch': {
      id: '/projects/$projectId/launch'
      path: '/launch'
      fullPath: '/projects/$projectId/launch'
      preLoaderRoute: typeof ProjectsProjectIdLaunchRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/book': {
      id: '/projects/$projectId/book'
      path: '/book'
      fullPath: '/projects/$projectId/book'
      preLoaderRoute: typeof ProjectsProjectIdBookRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/_hub/$projectId/voice': {
      id: '/_hub/$projectId/voice'
      path: '/voice'
      fullPath: '/$projectId/voice'
      preLoaderRoute: typeof HubProjectIdVoiceRouteImport
      parentRoute: typeof HubProjectIdRoute
    }
    '/_hub/$projectId/outline': {
      id: '/_hub/$projectId/outline'
      path: '/outline'
      fullPath: '/$projectId/outline'
      preLoaderRoute: typeof HubProjectIdOutlineRouteImport
      parentRoute: typeof HubProjectIdRoute
    }
    '/_hub/$projectId/marketplace': {
      id: '/_hub/$projectId/marketplace'
      path: '/marketplace'
      fullPath: '/$projectId/marketplace'
      preLoaderRoute: typeof HubProjectIdMarketplaceRouteImport
      parentRoute: typeof HubProjectIdRoute
    }
    '/_hub/$projectId/canvas': {
      id: '/_hub/$projectId/canvas'
      path: '/canvas'
      fullPath: '/$projectId/canvas'
      preLoaderRoute: typeof HubProjectIdCanvasRouteImport
      parentRoute: typeof HubProjectIdRoute
    }
    '/_hub/$projectId/book': {
      id: '/_hub/$projectId/book'
      path: '/book'
      fullPath: '/$projectId/book'
      preLoaderRoute: typeof HubProjectIdBookRouteImport
      parentRoute: typeof HubProjectIdRoute
    }
    '/_hub/scripts/$scriptId/': {
      id: '/_hub/scripts/$scriptId/'
      path: '/scripts/$scriptId'
      fullPath: '/scripts/$scriptId/'
      preLoaderRoute: typeof HubScriptsScriptIdIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/blogs/$blogId/': {
      id: '/_hub/blogs/$blogId/'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId/'
      preLoaderRoute: typeof HubBlogsBlogIdIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/projects/$projectId/chapters/$chapterId': {
      id: '/projects/$projectId/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/projects/$projectId/chapters/$chapterId'
      preLoaderRoute: typeof ProjectsProjectIdChaptersChapterIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/_hub/scripts/$scriptId/structure': {
      id: '/_hub/scripts/$scriptId/structure'
      path: '/scripts/$scriptId/structure'
      fullPath: '/scripts/$scriptId/structure'
      preLoaderRoute: typeof HubScriptsScriptIdStructureRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/blogs/$blogId/structure': {
      id: '/_hub/blogs/$blogId/structure'
      path: '/blogs/$blogId/structure'
      fullPath: '/blogs/$blogId/structure'
      preLoaderRoute: typeof HubBlogsBlogIdStructureRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/$projectId/chapters/$chapterId': {
      id: '/_hub/$projectId/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/$projectId/chapters/$chapterId'
      preLoaderRoute: typeof HubProjectIdChaptersChapterIdRouteImport
      parentRoute: typeof HubProjectIdRoute
    }
    '/_hub/scripts/$scriptId/scenes/$sceneId': {
      id: '/_hub/scripts/$scriptId/scenes/$sceneId'
      path: '/scripts/$scriptId/scenes/$sceneId'
      fullPath: '/scripts/$scriptId/scenes/$sceneId'
      preLoaderRoute: typeof HubScriptsScriptIdScenesSceneIdRouteImport
      parentRoute: typeof HubRoute
    }
    '/_hub/blogs/$blogId/posts/$postId': {
      id: '/_hub/blogs/$blogId/posts/$postId'
      path: '/blogs/$blogId/posts/$postId'
      fullPath: '/blogs/$blogId/posts/$postId'
      preLoaderRoute: typeof HubBlogsBlogIdPostsPostIdRouteImport
      parentRoute: typeof HubRoute
    }
  }
}

interface HubProjectIdRouteChildren {
  HubProjectIdBookRoute: typeof HubProjectIdBookRoute
  HubProjectIdCanvasRoute: typeof HubProjectIdCanvasRoute
  HubProjectIdMarketplaceRoute: typeof HubProjectIdMarketplaceRoute
  HubProjectIdOutlineRoute: typeof HubProjectIdOutlineRoute
  HubProjectIdVoiceRoute: typeof HubProjectIdVoiceRoute
  HubProjectIdChaptersChapterIdRoute: typeof HubProjectIdChaptersChapterIdRoute
}

const HubProjectIdRouteChildren: HubProjectIdRouteChildren = {
  HubProjectIdBookRoute: HubProjectIdBookRoute,
  HubProjectIdCanvasRoute: HubProjectIdCanvasRoute,
  HubProjectIdMarketplaceRoute: HubProjectIdMarketplaceRoute,
  HubProjectIdOutlineRoute: HubProjectIdOutlineRoute,
  HubProjectIdVoiceRoute: HubProjectIdVoiceRoute,
  HubProjectIdChaptersChapterIdRoute: HubProjectIdChaptersChapterIdRoute,
}

const HubProjectIdRouteWithChildren = HubProjectIdRoute._addFileChildren(
  HubProjectIdRouteChildren,
)

interface HubRouteChildren {
  HubProjectIdRoute: typeof HubProjectIdRouteWithChildren
  HubComposeRoute: typeof HubComposeRoute
  HubComposeBlogRoute: typeof HubComposeBlogRoute
  HubComposeScriptRoute: typeof HubComposeScriptRoute
  HubIndexRoute: typeof HubIndexRoute
  HubBlogsBlogIdStructureRoute: typeof HubBlogsBlogIdStructureRoute
  HubScriptsScriptIdStructureRoute: typeof HubScriptsScriptIdStructureRoute
  HubBlogsBlogIdIndexRoute: typeof HubBlogsBlogIdIndexRoute
  HubScriptsScriptIdIndexRoute: typeof HubScriptsScriptIdIndexRoute
  HubBlogsBlogIdPostsPostIdRoute: typeof HubBlogsBlogIdPostsPostIdRoute
  HubScriptsScriptIdScenesSceneIdRoute: typeof HubScriptsScriptIdScenesSceneIdRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubProjectIdRoute: HubProjectIdRouteWithChildren,
  HubComposeRoute: HubComposeRoute,
  HubComposeBlogRoute: HubComposeBlogRoute,
  HubComposeScriptRoute: HubComposeScriptRoute,
  HubIndexRoute: HubIndexRoute,
  HubBlogsBlogIdStructureRoute: HubBlogsBlogIdStructureRoute,
  HubScriptsScriptIdStructureRoute: HubScriptsScriptIdStructureRoute,
  HubBlogsBlogIdIndexRoute: HubBlogsBlogIdIndexRoute,
  HubScriptsScriptIdIndexRoute: HubScriptsScriptIdIndexRoute,
  HubBlogsBlogIdPostsPostIdRoute: HubBlogsBlogIdPostsPostIdRoute,
  HubScriptsScriptIdScenesSceneIdRoute: HubScriptsScriptIdScenesSceneIdRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdBookRoute: typeof ProjectsProjectIdBookRoute
  ProjectsProjectIdLaunchRoute: typeof ProjectsProjectIdLaunchRoute
  ProjectsProjectIdChaptersChapterIdRoute: typeof ProjectsProjectIdChaptersChapterIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdBookRoute: ProjectsProjectIdBookRoute,
  ProjectsProjectIdLaunchRoute: ProjectsProjectIdLaunchRoute,
  ProjectsProjectIdChaptersChapterIdRoute:
    ProjectsProjectIdChaptersChapterIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  HubRoute: HubRouteWithChildren,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ScoutRoute: ScoutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WelcomeRoute: WelcomeRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
